### ISSUE TITLE
combining metrics

### ISSUE THREAD

**Issue by CuongNN218** [mgholamikn/ETran#1]
Dear @mgholamikn , 

First of all, thanks for your great work on open-source code for the community. However, I have a question related to how did you combine different metrics. As I read in the paper, the energy score will be added to other metrics just by the (+) operator. However, different metrics could result in different scores on different scales, which could outweigh the effects of the energy score. How did you address this? Should I normalize them following the same scale e.g., 0-1. I do read the code but I found that the energy score was commented as in line [347](https://github.com/mgholamikn/ETran/blob/main/metrics.py#L347). 

I hope you can clarify my question.

Thanks.

**Comment by mgholamikn** [comment]
I appreciate your interest in our work. Yes, different scores were scaled in [this line ](https://github.com/mgholamikn/ETran/blob/d4551ed8f41f4ed6eba08b9cc1a78bae178acd19/tw.py#L82C15-L82C20) before combining. The energy score is defined in [here](https://github.com/mgholamikn/ETran/blob/d4551ed8f41f4ed6eba08b9cc1a78bae178acd19/metrics.py#L1085).
